### ISSUE TITLE
Debugging the "ingeter out of range" error when ingestion big data (100GB)

### ISSUE THREAD

**Issue by nanjiangshu** [NBISweden/LocalEGA#119] opened 2017-09-21 08:33 UTC
When ingesting the big data (e.g. 100GB).  The data was moved to the `vault` successfully, but an error for the  `db` was found.

```
vault_1     | [  utils   ][DEBUG ] (L40) Exception: <class 'psycopg2.DataError'> in /usr/lib/python3.6
/site-packages/lega/vault.py on line: 59
vault_1     | [    db    ][DEBUG ] (L94) Setting error for 2: integer out of range
```

**Comment by silverdaz** [comment] 2018-04-11 06:59
Can you still reproduce that bug (after all the changes we made)?

Here is my guess: The vault script, after moving the file, writes to the database the size of the file....which is too big to fit in the field. We need to update the database schema in such a case.

**Comment by dtitov** [comment] 2018-06-28 09:52
I guess this is not the case anymore since we are not ingesting "big data" (at least not the data itself, but a small header). Should we close it?

**Closed** 2018-07-01 21:37 UTC
Labels: bug
